kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: node:18.20.4-alpine3.20
    commands:
      - npm ci
      - npm run build

  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/vue-poker-timer
      tags: beta
    when:
      branch:
        - main
        - release/*

  - name: release
    image: plugins/docker
    settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    repo: rubasace/vue-poker-timer
    tags: ${CI_BUILD_TARGET}
    when:
      event:
        - promote
trigger:
  event:
    - push
    - promote