---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: node:18.20.4-alpine3.20
    commands:
      - npm ci
      - npm run build

  - name: release-beta
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/vue-poker-timer
      tags: beta
    when:
      event:
        - push
      branch:
        - main

  - name: release-stable
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/vue-poker-timer
      tags: ${CI_BUILD_TARGET}
    when:
      event:
        - promote
trigger:
  event:
    - push
    - promote
---
kind: signature
hmac: b74f151ce700519809a3419414dc169c2f0d893ec8555c804cbeff1742374391

...
